// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwkljwdqnlsrxttonafl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53a2xqd2Rxbmxzcnh0dG9uYWZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNjYxNzYsImV4cCI6MjA3MDg0MjE3Nn0.boYk_O4qsl7cSkeq7Nr6dizhcA18UvJw3pdg7-WWOBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});